### ISSUE TITLE
Understanding gas calculations: How is `paymasterVerificationGasLimit` estimated?

### ISSUE THREAD

**Issue by matthiasgeihs** [pimlicolabs/alto#272]
Hey, I'm trying to understand how gas estimations work. In particular, looking at `paymasterVerificationGasLimit`.

What I do understand: `EntryPointSimulations.sol` is used to simulate operations and thereby measure gas.

What I don't understand: The return type [`struct ExecutionResult`](https://github.com/pimlicolabs/alto/blob/12ab4854bb338487254f06c4d0760f5d2134ffb3/contracts/src/PimlicoEntryPointSimulations/IEntryPointSimulations.sol#L15) of `simulateHandleOP` does not include `paymasterVerificationGasLimit`, however, the `EntryPointV07SimulationsAbi` does have this field in the return value of this function (see [here](https://github.com/pimlicolabs/alto/blob/12ab4854bb338487254f06c4d0760f5d2134ffb3/src/types/contracts/EntryPointSimulations.ts#L763)).

How is that possible? And how is that value calculated on the contract side?

**Comment by mouseless0x** [comment]
Hey, I believe those contracts were out of date at the time, the contracts dir has since been deleted from Alto and moved to a seperate repo ([entrypoint-estimations](https://github.com/pimlicolabs/entrypoint-estimations/tree/e333fab73cadefb67f54f638666c8c92966b03aa)). The [ExecutionResult](https://github.com/pimlicolabs/entrypoint-estimations/blob/e333fab73cadefb67f54f638666c8c92966b03aa/src/v07/IEntryPointSimulations.sol#L25-L26) struct does contain `paymasterVerificationGasLimit`, and this field is populated during simulation by calling the EntryPoint's `_validatePrepayment` method. 

Let me know if you have any further questions:)
