### ISSUE TITLE
Question: How is this bundler different than the existing Typescript bundlers?

### ISSUE THREAD

**Issue by emailtovamos** [pimlicolabs/alto#32]
Just heard about alto today so curious about how it differs from the existing ones. 

Will look forward to explore more.

**Comment by kanthgithub** [comment]
- varies on multiple aspects. but follow common specs
- such as skandha which is another bundler opens-source implemented on typescript, uses rocksdb to persist userops in mempool where as alto is inmemory
- flow of a userOp since submission remains same but vary in how they are implemented
- i will list all shortly for differences in implementation of alto vs skandha 
   its easy to compare as both are typescript based
